version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: currency_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d currency_db"]
      interval: 1s
      timeout: 1s
      retries: 5

  migrate:
    image: migrate/migrate
    command: >
      -path /migrations
      -database postgres://admin:password@postgres:5432/currency_db?sslmode=disable 
      up
    volumes:
      - ./currency/internal/migrations:/migrations
    depends_on:
      postgres:
        condition: service_healthy

  auth-generator:
    image: andrianovartemii/gm-test-task-auth-generator:latest
    ports:
      - "8082:8080"
    environment:
      AUTH_TOKEN_LIFETIME: 2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 1s
      timeout: 1s
      retries: 5
